"""Initial schema creation

Revision ID: ac02162677a9
Revises: None
Create Date: 2026-06-20 15:12:49.532519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.app.core.database import SafeVector


# revision identifiers, used by Alembic.
revision: str = 'ac02162677a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False, comment='Unique identifier for the audit transaction log'),
    sa.Column('session_id', sa.String(length=255), nullable=False, comment='Tracks the specific client browser session or API call grouping'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='The execution timestamp of the security transaction'),
    sa.Column('raw_input', sa.String(), nullable=False, comment='The original, unsanitized user query (stored encrypted via AES-GCM)'),
    sa.Column('sanitized_input', sa.String(), nullable=True, comment='The parsed and clean user query after redacting PII or removing injections'),
    sa.Column('overall_risk_score', sa.Float(), nullable=False, comment='Synthesized threat metric (0.0 = Safe, 1.0 = Critical)'),
    sa.Column('policy_action', sa.String(length=50), nullable=False, comment='Decision outcome: ALLOW, BLOCK, REDACTED, or HUMAN_REVIEW'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('exploit_signatures',
    sa.Column('signature_id', sa.UUID(), nullable=False, comment='Unique identifier for the signature exploit record'),
    sa.Column('exploit_pattern', sa.String(), nullable=False, comment='The text fragment representing the jailbreak template'),
    sa.Column('embedding', SafeVector(1536), nullable=False, comment='Float vector representation (1536 dimensions) for similarity search'),
    sa.Column('added_at', sa.DateTime(), nullable=False, comment='Timestamp representing when this signature pattern was indexed'),
    sa.PrimaryKeyConstraint('signature_id')
    )
    op.create_table('human_approvals',
    sa.Column('approval_id', sa.UUID(), nullable=False, comment='Unique identifier for the human review block task'),
    sa.Column('log_id', sa.UUID(), nullable=False, comment='Links back to the target AuditLog transaction being reviewed'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='State of approval: PENDING, APPROVED, or REJECTED'),
    sa.Column('reviewer_id', sa.String(length=100), nullable=True, comment='Identifier for the administrator executing the review'),
    sa.Column('review_notes', sa.Text(), nullable=True, comment='Notes supplied by the reviewer justifying the action decision'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Creation timestamp of the human approval ticket'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='Completion timestamp representing when the review decision was saved'),
    sa.ForeignKeyConstraint(['log_id'], ['audit_logs.log_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_index(op.f('ix_human_approvals_log_id'), 'human_approvals', ['log_id'], unique=False)
    op.create_table('security_events',
    sa.Column('event_id', sa.UUID(), nullable=False, comment='Unique identifier for the security warning event'),
    sa.Column('log_id', sa.UUID(), nullable=False, comment='Foreign key linking back to the primary parent AuditLog record'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Timestamp of event trigger'),
    sa.Column('agent_source', sa.String(length=50), nullable=False, comment='Name of the agent that triggered the warning: INJECTION, PII, FILE, ACTION_GUARD'),
    sa.Column('trigger_type', sa.String(length=255), nullable=False, comment='Specific threat classification (e.g., Jailbreak Attempt, API Leak, SSN Masked)'),
    sa.Column('severity_level', sa.String(length=20), nullable=False, comment='Level of severity: LOW, MEDIUM, HIGH, CRITICAL'),
    sa.Column('details', sa.JSON(), nullable=True, comment='Contextual telemetry metadata detailing target parameters or matching lines'),
    sa.ForeignKeyConstraint(['log_id'], ['audit_logs.log_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_security_events_log_id'), 'security_events', ['log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_events_log_id'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_human_approvals_log_id'), table_name='human_approvals')
    op.drop_table('human_approvals')
    op.drop_table('exploit_signatures')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
